### ISSUE TITLE
Problem when installing agent on Debian

### ISSUE THREAD

**Issue by laurent-ta** [vFense/vFenseAgent-nix#18]
Hi guys,

I'm testing Vfense and I have some trouble with the Agent (0.7.2) only on my debian server (Debian 7.5).
Here is what it shows in the log in /opt/TopPatch/agent_install_failure.log

2014-08-22 16:44:23.859615 : Traceback (most recent call last):
  File "./install", line 1111, in install
    self._clean_up()
  File "./install", line 1020, in _clean_up
    self._deb_remove_service()
  File "./install", line 1016, in _deb_remove_service
    raise Exception(err)
Exception: perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
    LANGUAGE = "fr",
    LC_ALL = (unset),
    LC_PAPER = "fr_FR.UTF-8",
    LC_ADDRESS = "fr_FR.UTF-8",
    LC_MONETARY = "fr_FR.UTF-8",
    LC_NUMERIC = "fr_FR.UTF-8",
    LC_TELEPHONE = "fr_FR.UTF-8",
    LC_IDENTIFICATION = "fr_FR.UTF-8",
    LC_MEASUREMENT = "fr_FR.UTF-8",
    LC_TIME = "fr_FR.UTF-8",
    LC_NAME = "fr_FR.UTF-8",
    LANG = "eu_FR.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

If you have any idea on how I could fix that, it would be great !!

Thx for this awesome project !

Laurent

**Comment by laurent-ta** [comment]
I found the solution ! It just fixed the locale settings !

**Comment by linuxdynasty** [comment]
Awesome, what exactly did you do, so we can document this in the wiki, cause I'm sure other people are running into this issue as well.

**Comment by laurent-ta** [comment]
I needed to fix the locale settings.

First you need to check if there is something wrong when you type the command "locale".
It used to show me a missing field for LC_ALL=(unset) so you need to fix it with a command 
"dpkg-reconfigure locales" and then "locale-gen".

And now when I do a "locale" command :

LANG=fr_FR.UTF-8
LANGUAGE=fr
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=fr_FR.UTF-8
